# fly.toml app configuration file generated for ai-article-writer on 2024-08-04T15:02:15-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-article-writer'
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1  
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

